---
title: Output Design
---
classDiagram

    OllamaNotInstalledError ..> AutoDevError
    ModelTimeoutError ..> AutoDevError
    ModelNameError ..> AutoDevError

    Services ..> OllamaNotInstalledError
    Services ..> ModelTimeoutError
    Services ..> ModelNameError

    Termination ..> AutoDevError
    Termination ..> sys

    Handlers ..> Termination
