---
title: File System Design
---
classDiagram
    class FileSystem {
        geneateTree(path: str): FileSystemObject
    }

    class FileSystemObject {
        name: str
        isDir: bool
        contents: None | str
        children(): List[FileSystemObject]
        parent(): FileSystemObject
    }

    FileSystem ..> FileSystemObject
