---
title: File System Design
---
classDiagram
    class FileSystem {
        generate_tree(path: str, depth: int) -> FileSystemObject
    }

    class FileSystemObject {
        __init__(name: str, contents: Optional[str] = None):
        name: str
        is_dir: bool
        contents: str
        children: List[FileSystemObject]
    }

    FileSystem ..> FileSystemObject
