---
title: Handlers Design
---
classDiagram
    class ConfigGeneratorHandler {
        generateConfig(project_path, model, prompt_path, quiet)
    }

    class DirenvGeneratorHandler {
        generateDirenv(project_path, quiet)
    }

    ConfigGeneratorHandler  ..> Services
    DirenvGeneratorHandler  ..> Services

