---
title: LLM Server Module Class Diagram
---
classDiagram

    class Server {
        start()
        is_model_installed(model_name: str): bool
        install_model(model_name: str)
        uninstall_model(model_name: str)
    }

    class Model {
        __init__(model_name: str)
        ask(message: str): str
    }

    class Services {
        install(model_name: str)
        uninstall(model_name: str)
    }

    Model ..> Server
    Services ..> Server
