---
title: LLM Server Module Class Diagram
---
classDiagram

    class Server {
        start()
        is_model_installed(model_name: str): bool
        install_model(model_name: str)
        uninstall_model(model_name: str)
        get_api_base(): str
        get_server_model_name(name: str): str
    }

    class Model {
        add_direnv(project_path: str)
    }

    Model ..> Server
