---
title: Model Design
---
classDiagram
    class Model {
        __init__(name: str, timeout: int = 5000) -> Model
        ask(message: str) -> str
    }

    class litellm {
        <<package>>
    }

    Model ..> litellm

