---
title: Output Design
---
classDiagram
    class Output {
        init(quiet: bool)
        create_file(name: str, contents: str, path: str)
        cli_print(message: str)
        cli_print_error(message: str)
    }

    class os {
        <<builtin package>>
    }

    class rich {
        <<package>>
    }

    Output ..> os
    Output ..> rich
