---
title: Output Design
---
classDiagram
    class Output {
        init(quiet: bool)
        create_file(name: str, contents: str, path: str)
        cli_print(print_type: PrintType, *message: str)
    }

    class rich {
        <<package>>
    }

    Output ..> rich
