---
title: Services Design
---
classDiagram

    class Configuration {
        add_config(model: str, project_path: str, prompt_path: str) 
    }

    class Direnv {
        add_direnv(project_path: str)
    }

    class Generator {
        generate_config(model_name: str, project_path: str, prompt_path: str) -> str
    }

    class Model {
        __init__(name: str, timeout: int = 5000) -> Model
        ask(message: str) -> str
    }

    class Prompt {
        get_prompt(prompt_path: str, project_path: str) -> str
    }

    class Output {
        init(quiet: bool = False)
        create_file(name: str, contents: str, path: str)
        cli_print(print_type: PrintType, *message: str)
    }

    class Reader {
        read_file(path: str) -> str
        read_dir(path: str) -> FileSystemObject
    }

    Direnv ..> Output
    Configuration ..> Output
    Configuration ..> Generator
    Generator ..> Model
    Generator ..> Prompt
    Prompt ..> Reader
