---
title: Services Design
---
classDiagram

    class Configuration {
        add_config(model: str, project_path: str, prompt_path: str) 
    }

    class Direnv {
        add_direnv(project_path: str)
    }

    class Install {
        install(model_name: str)
    }

    class Uninstall {
        uninstall(model_name: str)
    }

    class Generator {
        generate_config(model_name: str, project_path: str, prompt_path: str) -> str
    }

    class Model {
        ask(model_name: str, message: str) -> str
    }

    class Prompt {
        get_prompt(prompt_path: str, project_path: str) -> str
    }

    class Output {
        init(quiet: bool = False)
        create_file(name: str, contents: str, path: str)
        cli_print(print_type: PrintType, *message: str)
    }

    class FileSystem {
        generate_tree(path: str, depth: int) -> FileSystemObject
    }

    Direnv ..> Output
    Configuration ..> Output
    Install ..> Output
    Uninstall ..> Output
    Configuration ..> Generator
    Generator ..> Model
    Generator ..> Prompt
    Prompt ..> FileSystem
