plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

author: 
  name: Leonardo Randacio
  email: "leonardorandacio@gmail.com"

minima:
  skin: auto
  social_links:
      icon: github
      url: "https://github.com/Oldranda1414/AutoDev"
  hide_site_feed_link: true
  nav_pages:
    - introduction.md
    - requirements.md
    - architectural-design.md
    - detailed-design.md
    - implementation.md
    - testing.md
    - conclusion.md

